version: "3.1"

services:
  mongo_db:
    image: mongo
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"

  api-books:
    image: omarang/api-books:latest
    ports:
      - "3000:3000"
    environment:
      BOOK_URL: https://raw.githubusercontent.com/omarchalito/api-nodejs-libros/master/src/seed/services/books.csv
      DB_HOST: mongodb://mongo_db:27017/books_db
      ENV: production
      PORT: 3000